/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
/**
 *
 * @author hp
 */
public class dashboardadmin extends javax.swing.JFrame {

    /**
     * Creates new form dashboardadmin
     */
    public dashboardadmin() {
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
        }
    });
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
    tampilkanStatistik();                                                                                                                   lblWelcome.setText("Selamat Datang, Admin: " + Session.getAdmin());
}
    private void tampilkanStatistik() {
    try {
        Connection conn = KoneksiDB.getConnection();

        // Jumlah Mahasiswa
        String sqlMhs = "SELECT COUNT(*) AS total_mhs FROM mahasiswa";
        PreparedStatement pstMhs = conn.prepareStatement(sqlMhs);
        ResultSet rsMhs = pstMhs.executeQuery();
        if (rsMhs.next()) {
            lblMahasiswa.setText("Mahasiswa Aktif: " + rsMhs.getInt("total_mhs"));
        }

        // Jumlah Dosen
        String sqlDosen = "SELECT COUNT(*) AS total_dosen FROM dosen";
        PreparedStatement pstDosen = conn.prepareStatement(sqlDosen);
        ResultSet rsDosen = pstDosen.executeQuery();
        if (rsDosen.next()) {
            lblDosen.setText("Dosen Pembimbing: " + rsDosen.getInt("total_dosen"));
        }

        // Jumlah Pengajuan & Status
        int total = 0, disetujui = 0, revisi = 0, menunggu = 0;
        String sqlBim = "SELECT status_pengajuan FROM bimbingan";
        PreparedStatement pstBim = conn.prepareStatement(sqlBim);
        ResultSet rsBim = pstBim.executeQuery();
        while (rsBim.next()) {
            total++;
            String status = rsBim.getString("status_pengajuan");
            if (status.equalsIgnoreCase("Disetujui")) disetujui++;
            else if (status.equalsIgnoreCase("Perlu Revisi")) revisi++;
            else if (status.equalsIgnoreCase("Menunggu")) menunggu++;
        }
        lblPengajuan.setText("Total Pengajuan: " + total);
        lblDisetujui.setText("Disetujui: " + disetujui);
        lblRevisi.setText("Perlu Revisi: " + revisi);
        lblMenunggu.setText("Menunggu: " + menunggu);

        // Jadwal Bimbingan
        String sqlJadwal = "SELECT COUNT(*) AS total_jadwal FROM jadwal_bimbingan";
        PreparedStatement pstJadwal = conn.prepareStatement(sqlJadwal);
        ResultSet rsJadwal = pstJadwal.executeQuery();
        if (rsJadwal.next()) {
            lblJadwal.setText("Jumlah Penjadwalan: " + rsJadwal.getInt("total_jadwal"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat statistik: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblDosen = new javax.swing.JLabel();
        lblPengajuan = new javax.swing.JLabel();
        lblDisetujui = new javax.swing.JLabel();
        lblRevisi = new javax.swing.JLabel();
        lblMenunggu = new javax.swing.JLabel();
        lblJadwal = new javax.swing.JLabel();
        lblMahasiswa = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Dasboard Admin");

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWelcome.setText("Selamat Datang, Admin :");

        lblDosen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDosen.setText("Mahasiswa Aktif :");

        lblPengajuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPengajuan.setText("Total Pengajuan :");

        lblDisetujui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDisetujui.setText("- Disetujui :");

        lblRevisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRevisi.setText("- Perlu Revisi :");

        lblMenunggu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMenunggu.setText("- Menunggu :");

        lblJadwal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJadwal.setText("Jumlah Penjadwalan :");

        lblMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMahasiswa.setText("Dosen Pembimbing :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMahasiswa)
                            .addComponent(lblDosen)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDisetujui)
                                .addComponent(lblPengajuan)
                                .addComponent(lblRevisi)
                                .addComponent(lblMenunggu))
                            .addComponent(lblJadwal)
                            .addComponent(lblWelcome))))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDosen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPengajuan)
                .addGap(14, 14, 14)
                .addComponent(lblDisetujui)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRevisi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMenunggu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblJadwal)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("Manajemen Data");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Monitoring Progres");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Arsip Bimbingan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Pengaturan Sistem");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);
        jMenu1.add(jSeparator1);

        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Logout");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new ManajemenDataAdmin().setVisible(true); // buka form profil
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new MonitoringProgressMahasiswa().setVisible(true); // buka form profil
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new AsipBimbinganSkripsi().setVisible(true); // buka form profil
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new PengaturanSistemAdmin().setVisible(true); // buka form profil
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Logout dari sistem?", "Logout", JOptionPane.YES_NO_OPTION);
    if (result == JOptionPane.YES_OPTION) {
        Session.setAdmin(null); // jika pakai session
        dispose();
        new SISKRIP().setVisible(true);
    }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboardadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboardadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboardadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboardadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboardadmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblDisetujui;
    private javax.swing.JLabel lblDosen;
    private javax.swing.JLabel lblJadwal;
    private javax.swing.JLabel lblMahasiswa;
    private javax.swing.JLabel lblMenunggu;
    private javax.swing.JLabel lblPengajuan;
    private javax.swing.JLabel lblRevisi;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
