/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author hp
 */
public class dashboarddosen extends javax.swing.JFrame {

    /**
     * Creates new form dashboarddosen
     */
    public dashboarddosen() {
        initComponents();
        String nidn = Session.getNIDN();
         lblWelcome.setText("Selamat datang, NIDN: " + nidn);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
        }
    });
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
         tampilkanDataDosen();
         tampilkanRingkasan();
}
    private void tampilkanDataDosen() {
    try {
        Connection conn = KoneksiDB.getConnection();
        String sql = "SELECT password FROM dosen WHERE nidn = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, Session.getNIDN());
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            lblWelcome.setText("Selamat datang, " + rs.getString("password") + " (NIDN: " + Session.getNIDN() + ")");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data dosen: " + e.getMessage());
    }
}
    private void tampilkanRingkasan() {
    try {
        Connection conn = KoneksiDB.getConnection();

        // Jumlah Mahasiswa
        String sql1 = "SELECT COUNT(*) AS total FROM mahasiswa WHERE nidn_pembimbing = ?";
        PreparedStatement pst1 = conn.prepareStatement(sql1);
        pst1.setString(1, Session.getNIDN());
        ResultSet rs1 = pst1.executeQuery();
        if (rs1.next()) {
            lblJumlahMhs.setText("Mahasiswa bimbingan : " + rs1.getInt("total") + " orang");
        }

        // Jumlah Pengajuan Menunggu
        String sql2 = "SELECT COUNT(*) AS total FROM bimbingan WHERE status_pengajuan = 'Menunggu' AND nim IN (SELECT nim FROM mahasiswa WHERE nidn_pembimbing = ?)";
        PreparedStatement pst2 = conn.prepareStatement(sql2);
        pst2.setString(1, Session.getNIDN());
        ResultSet rs2 = pst2.executeQuery();
        if (rs2.next()) {
            lblJumlahPengajuan.setText("Pengajuan skripsi : " + rs2.getInt("total") + " menunggu");
        }

        // Jadwal Disetujui Hari Ini
        String sql3 = "SELECT COUNT(*) AS total FROM jadwal_bimbingan WHERE status = 'Disetujui' AND tanggal = CURDATE() AND nim IN (SELECT nim FROM mahasiswa WHERE nidn_pembimbing = ?)";
        PreparedStatement pst3 = conn.prepareStatement(sql3);
        pst3.setString(1, Session.getNIDN());
        ResultSet rs3 = pst3.executeQuery();
        if (rs3.next()) {
            lblJumlahJadwal.setText("Jadwal hari ini     : " + rs3.getInt("total") + " disetujui");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat ringkasan: " + e.getMessage());
    }
}

   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblJumlahMhs = new javax.swing.JLabel();
        lblJumlahPengajuan = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblJumlahJadwal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWelcome.setText("NIDN");

        lblJumlahMhs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJumlahMhs.setText("Mahasiswa Bimbingan :");

        lblJumlahPengajuan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJumlahPengajuan.setText("Pengajuan Skripsi :");

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNama.setText("Ringkasan :");

        lblJumlahJadwal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJumlahJadwal.setText("Jadwal Hari Ini :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJumlahJadwal)
                    .addComponent(lblNama)
                    .addComponent(lblWelcome)
                    .addComponent(lblJumlahMhs)
                    .addComponent(lblJumlahPengajuan))
                .addContainerGap(435, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblWelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJumlahMhs)
                .addGap(18, 18, 18)
                .addComponent(lblJumlahPengajuan)
                .addGap(18, 18, 18)
                .addComponent(lblJumlahJadwal)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("Profil dosen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Review & Revisi");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Penjadwalan Bimbingan");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       new profil_dosenn().setVisible(true); // buka form profil
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      new Penjadwalan_Bimbingan_Mahasiswa().setVisible(true); // buka form profil
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       new ReviewdanRevisiBimbingan_().setVisible(true); // buka form profil
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboarddosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboarddosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboarddosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboarddosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboarddosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblJumlahJadwal;
    private javax.swing.JLabel lblJumlahMhs;
    private javax.swing.JLabel lblJumlahPengajuan;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
