/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hp
 */
public class LaporanPerkembanganMhsw extends javax.swing.JFrame {

    /**
     * Creates new form LaporanPerkembanganMhsw
     */
    public LaporanPerkembanganMhsw() {
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
        }
    });
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
    tampilkanDataDosen();
    tampilkanLaporan();
}
    private void tampilkanDataDosen() {
    try {
        Connection conn = KoneksiDB.getConnection();
        String sql = "SELECT password FROM dosen WHERE nidn = ?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, Session.getNIDN());
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            lblNidn.setText("NIDN  : " + Session.getNIDN());
            lblNama.setText("Nama  : " + rs.getString("password"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data dosen: " + e.getMessage());
    }
}
    private void tampilkanLaporan() {
    int total = 0, disetujui = 0, revisi = 0, menunggu = 0;

    try {
        Connection conn = KoneksiDB.getConnection();

        // Jumlah mahasiswa bimbingan
        String sqlMhs = "SELECT COUNT(*) AS total_mhs FROM mahasiswa WHERE nidn_pembimbing = ?";
        PreparedStatement pstMhs = conn.prepareStatement(sqlMhs);
        pstMhs.setString(1, Session.getNIDN());
        ResultSet rsMhs = pstMhs.executeQuery();
        if (rsMhs.next()) {
            lblJumlahMhs.setText("Jumlah Mahasiswa Bimbingan: " + rsMhs.getInt("total_mhs"));
        }

        // Pengajuan oleh mahasiswa bimbingan
        String sql = "SELECT status_pengajuan FROM bimbingan WHERE nim IN (SELECT nim FROM mahasiswa WHERE nidn_pembimbing = ?)";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, Session.getNIDN());
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            total++;
            String status = rs.getString("status_pengajuan");
            if (status.equalsIgnoreCase("Disetujui")) disetujui++;
            else if (status.equalsIgnoreCase("Perlu Revisi")) revisi++;
            else if (status.equalsIgnoreCase("Menunggu")) menunggu++;
        }

        lblTotal.setText("Total Pengajuan     : " + total);
        lblDisetujui.setText("Disetujui           : " + disetujui);
        lblRevisi.setText("Perlu Revisi        : " + revisi);
        lblMenunggu.setText("Menunggu Persetujuan: " + menunggu);

        // Opsional progress bar
        int progress = (total == 0) ? 0 : (disetujui * 100 / total);
        progressBar.setValue(progress);
        progressBar.setString(progress + "%");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat laporan: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNidn = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblJumlahMhs = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblDisetujui = new javax.swing.JLabel();
        lblRevisi = new javax.swing.JLabel();
        lblMenunggu = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        btnKembali = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lblNidn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNidn.setText("NIDN :");

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNama.setText("NAMA:");

        lblJumlahMhs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJumlahMhs.setText("Jumlah Mahasiswa Bimbingan :");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTotal.setText("Total Pengajuan :");

        lblDisetujui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDisetujui.setText("Disetujui :");

        lblRevisi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRevisi.setText("Perlu Revisi");

        lblMenunggu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMenunggu.setText("Menunggu Persetujuan :");

        btnKembali.setBackground(new java.awt.Color(0, 0, 0));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addGap(266, 266, 266))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMenunggu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNama)
                    .addComponent(lblNidn)
                    .addComponent(lblJumlahMhs)
                    .addComponent(lblTotal)
                    .addComponent(lblDisetujui)
                    .addComponent(lblRevisi))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblNidn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNama)
                .addGap(18, 18, 18)
                .addComponent(lblJumlahMhs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDisetujui)
                .addGap(7, 7, 7)
                .addComponent(lblRevisi)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMenunggu)
                        .addGap(31, 31, 31)
                        .addComponent(btnKembali))
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("Pengaturan Akun");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        this.dispose();
    new dashboarddosen().setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new PengaturanAkunDosen().setVisible(true); // buka form profil
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanPerkembanganMhsw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanPerkembanganMhsw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanPerkembanganMhsw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanPerkembanganMhsw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanPerkembanganMhsw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDisetujui;
    private javax.swing.JLabel lblJumlahMhs;
    private javax.swing.JLabel lblMenunggu;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNidn;
    private javax.swing.JLabel lblRevisi;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
