/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hp
 */
public class ManajemenDataAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ManajemenDataAdmin
     */
    public ManajemenDataAdmin() {
        initComponents();
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
        }
    });
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
    tampilkanDataMahasiswa();
    tampilkanDataDosen();
}
    private void tampilkanDataMahasiswa() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NIM");
    model.addColumn("Nama");
    model.addColumn("NIDN Pembimbing");

    try {
        Connection conn = KoneksiDB.getConnection();
        String sql = "SELECT * FROM mahasiswa";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("nim"),
                rs.getString("nama"),
                rs.getString("nidn_pembimbing")
            });
        }

        tableMahasiswa.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat mahasiswa: " + e.getMessage());
    }
}
    private void tampilkanDataDosen() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NIDN");
    model.addColumn("password");

    try {
        Connection conn = KoneksiDB.getConnection();
        String sql = "SELECT * FROM dosen";
        PreparedStatement pst = conn.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("nidn"),
                rs.getString("password")
            });
        }

        tableDosen.setModel(model);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat dosen: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDosen = new javax.swing.JTable();
        btnEditMhs = new javax.swing.JButton();
        btnEditDosen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Manajemen Data Admin");

        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableMahasiswa);

        tableDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableDosen);

        btnEditMhs.setBackground(new java.awt.Color(0, 0, 0));
        btnEditMhs.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditMhs.setForeground(new java.awt.Color(255, 255, 255));
        btnEditMhs.setText("Edit Mahasiswa");
        btnEditMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMhsActionPerformed(evt);
            }
        });

        btnEditDosen.setBackground(new java.awt.Color(0, 0, 0));
        btnEditDosen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditDosen.setForeground(new java.awt.Color(255, 255, 255));
        btnEditDosen.setText("Edit Dosen");
        btnEditDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditDosenActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEditMhs)
                                .addGap(90, 90, 90)
                                .addComponent(btnEditDosen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditMhs)
                    .addComponent(btnEditDosen)
                    .addComponent(jButton1))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Notifikasi Umum & Info Akun Admin");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMhsActionPerformed
int row = tableMahasiswa.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris mahasiswa yang ingin diedit.");
        return;
    }

    String nim = tableMahasiswa.getValueAt(row, 0).toString();
    String namaLama = tableMahasiswa.getValueAt(row, 1).toString();
    String nidnLama = tableMahasiswa.getValueAt(row, 2).toString();

    String namaBaru = JOptionPane.showInputDialog(this, "Edit Nama Mahasiswa:", namaLama);
    String nidnBaru = JOptionPane.showInputDialog(this, "Edit NIDN Pembimbing:", nidnLama);

    if (namaBaru != null && nidnBaru != null) {
        try {
            Connection conn = KoneksiDB.getConnection();
            String sql = "UPDATE mahasiswa SET nama = ?, nidn_pembimbing = ? WHERE nim = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, namaBaru);
            pst.setString(2, nidnBaru);
            pst.setString(3, nim);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data mahasiswa berhasil diperbarui.");
            tampilkanDataMahasiswa();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui: " + e.getMessage());
        }
    }  
    }//GEN-LAST:event_btnEditMhsActionPerformed

    private void btnEditDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDosenActionPerformed
        int row = tableDosen.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris dosen yang ingin diedit.");
        return;
    }

    String nidn = tableDosen.getValueAt(row, 0).toString();
    String namaLama = tableDosen.getValueAt(row, 1).toString();

    String namaBaru = JOptionPane.showInputDialog(this, "Edit Nama Dosen:", namaLama);

    if (namaBaru != null) {
        try {
            Connection conn = KoneksiDB.getConnection();
            String sql = "UPDATE dosen SET password = ? WHERE nidn = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, namaBaru);
            pst.setString(2, nidn);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data dosen berhasil diperbarui.");
            tampilkanDataDosen();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnEditDosenActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         String username = Session.getAdmin(); // Ambil admin yang sedang login

    String pesan = "👤 Admin Aktif : " + username + "\n\n"
                 + "🔔 Notifikasi Umum:\n"
                 + "- 2 Mahasiswa belum memiliki pembimbing\n"
                 + "- 5 Jadwal bimbingan menunggu persetujuan dosen\n"
                 + "- 1 skripsi selesai dan telah diarsipkan";

    JOptionPane.showMessageDialog(this, pesan, "Info Admin & Notifikasi", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new dashboardadmin().setVisible(true);
    this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManajemenDataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManajemenDataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManajemenDataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManajemenDataAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManajemenDataAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditDosen;
    private javax.swing.JButton btnEditMhs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDosen;
    private javax.swing.JTable tableMahasiswa;
    // End of variables declaration//GEN-END:variables
}
