/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author hp
 */
public class PengaturanSistemAdmin extends javax.swing.JFrame {
    private String tipeUser = "mahasiswa"; // default pilihan
   
   
    /**
     * Creates new form PengaturanSistemAdmin
     */
    public PengaturanSistemAdmin() {
        initComponents();
        groupUserType = new ButtonGroup();
        groupUserType.add(rbMahasiswa);
        groupUserType.add(rbDosen);

        rbMahasiswa.setSelected(true); // default // default
        this.addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
        }
    });
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        tampilkanDataUser(tipeUser);
    }

    private void tampilkanDataUser(String tipe) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(tipe.equals("mahasiswa") ? "NIM" : "NIDN");
        model.addColumn("Nama");

        try {
            Connection conn = KoneksiDB.getConnection();
            String sql = tipe.equals("mahasiswa") ?
                "SELECT nim AS id, nama FROM mahasiswa" :
                "SELECT nidn AS id, password FROM dosen";

            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id"),
                     
                tipe.equals("mahasiswa") ? rs.getString("nama") : rs.getString("password")
           
                });
            }

            tableUser.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupUserType = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbDosen = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        btnResetPass = new javax.swing.JButton();
        btnHapusUser = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        rbMahasiswa = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Pengaturan Sistem Admin");

        rbDosen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbDosen.setText("Dosen");
        rbDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDosenActionPerformed(evt);
            }
        });

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableUser);

        btnResetPass.setBackground(new java.awt.Color(0, 0, 0));
        btnResetPass.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetPass.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPass.setText("Reset Password");
        btnResetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPassActionPerformed(evt);
            }
        });

        btnHapusUser.setBackground(new java.awt.Color(0, 0, 0));
        btnHapusUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapusUser.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusUser.setText("Hapus User");
        btnHapusUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusUserActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(0, 0, 0));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        rbMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        rbMahasiswa.setText("Mahasiswa");
        rbMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMahasiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnResetPass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapusUser)
                                .addGap(69, 69, 69)
                                .addComponent(btnKembali))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbMahasiswa)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbDosen)))))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rbMahasiswa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbDosen)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnHapusUser)
                    .addComponent(btnResetPass))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPassActionPerformed
     int row = tableUser.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih user terlebih dahulu.");
        return;
    }

    String id = tableUser.getValueAt(row, 0).toString();
    String kolomId = tipeUser.equals("mahasiswa") ? "nim" : "nidn";
    String kolomPassword = tipeUser.equals("mahasiswa") ? "nama" : "password"; // gunakan ini

    String newPass = JOptionPane.showInputDialog(this, "Masukkan password baru:");
    if (newPass != null && !newPass.isEmpty()) {
        try {
            Connection conn = KoneksiDB.getConnection();
            String sql = "UPDATE " + tipeUser + " SET " + kolomPassword + " = ? WHERE " + kolomId + " = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, newPass);
            pst.setString(2, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Password berhasil direset.");
            tampilkanDataUser(tipeUser); // ini akan refresh isi tabel

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal mereset password: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnResetPassActionPerformed

    private void rbDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDosenActionPerformed
         tipeUser = "dosen";
        tampilkanDataUser(tipeUser);
    }//GEN-LAST:event_rbDosenActionPerformed

    private void rbMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMahasiswaActionPerformed
        tipeUser = "mahasiswa";
        tampilkanDataUser(tipeUser);
    }//GEN-LAST:event_rbMahasiswaActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
       this.dispose();
        new dashboardadmin().setVisible(true);
    
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnHapusUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusUserActionPerformed
     int row = tableUser.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih user yang ingin dihapus.");
            return;
        }

        String id = tableUser.getValueAt(row, 0).toString();
        String kolom = tipeUser.equals("mahasiswa") ? "nim" : "nidn";

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus user ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection conn = KoneksiDB.getConnection();
                String sql = "DELETE FROM " + tipeUser + " WHERE " + kolom + " = ?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, id);
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this, "User berhasil dihapus.");
                tampilkanDataUser(tipeUser);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menghapus user: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengaturanSistemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengaturanSistemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengaturanSistemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengaturanSistemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengaturanSistemAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusUser;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnResetPass;
    private javax.swing.ButtonGroup groupUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbDosen;
    private javax.swing.JRadioButton rbMahasiswa;
    private javax.swing.JTable tableUser;
    // End of variables declaration//GEN-END:variables
}
